version: 2.1

workflows:
  deploy:
    jobs:
      - upload_to_pypi
#          filters:
#            branches:
#              only: v*.*

jobs:
  upload_to_pypi:
    docker:
      - image: python:3.6
    environment:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${TEST_PYPI_PASSWORD}
    steps:
      - checkout
      - run: pip3 install --upgrade setuptools wheel twine
      - run: >
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload --repository testpypi dist/*
